// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkybgtlhhnpplhqsntvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJreWJndGxoaG5wcGxocXNudHZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NzkyMDMsImV4cCI6MjA3MjQ1NTIwM30.gcU0abCMxmRaa1bfLKNNc9byZW9qO23WNFF0t0ifL_s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});